export const Galleries = [
  {
    galleryId: '1',
    title: 'Rzym',
    dateCreated: '2015-12-15T00:00:00+00:00',
    thumbUrl: '/assets/img/rzym.jpg',
    description: 'Kilka dni zwariowanego wypadu do Rzymu.',
    tags: [],
    photos: [],
  },
  {
    galleryId: '2',
    title: 'Maroko',
    dateCreated: '2015-08-07T00:00:00+00:00',
    thumbUrl: '/assets/img/maroko.jpg',
    description: 'Tydzień zwiedzania południowego Maroka z ojcem.',
    tags: [],
    photos: [],
  },
  {
    galleryId: '3',
    title: 'Tajlandia',
    dateCreated: '2014-11-10T00:00:00+00:00',
    thumbUrl: '/assets/img/tajlandia.jpg',
    description: 'Dwa tygodnie wycieczki po Tajlandii.',
    tags: [],
    photos: [],
  },
  {
    galleryId: '4',
    title: 'Kambodża',
    dateCreated: '2013-11-25T00:00:00+00:00',
    thumbUrl: '/assets/img/kambodza.jpg',
    description: 'Wypoczynek w Kambodży z przyjaciółmi.',
    tags: [],
    photos: [],
  },
  {
    galleryId: '5',
    title: 'Turcja',
    dateCreated: '2012-06-02T00:00:00+00:00',
    thumbUrl: '/assets/img/turcja.jpg',
    description: 'Zwiedzanie Turcji z rodziną',
    tags: [],
    photos: [],
  },
  {
    galleryId: '6',
    title: 'Chiny',
    dateCreated: '2011-10-18T00:00:00+00:00',
    thumbUrl: '/assets/img/chiny.jpg',
    description: 'Wycieczka dwutygodniowa do Chin.',
    tags: [],
    photos: [],
  },
];
